language: python

python:
  - "3.7.6"

install:
  - pip install -r requirements.txt
  
script:
  - python ./src/JRC2018_ds_tsv_for_curation.py --splits resources/flylight_combination_lines_2.tsv --filenames resources/JRC2018_Unisex_20X_split_fileNames1.csv --year 2020 --curator adm71 --template JRC2018Unisex_c --doi 10.1016/j.neuron.2017.03.010 --ds Strother2017